name: cibweb
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_auth: ^4.12.0
  animated_bottom_navigation_bar: ^1.3.0
  qr_code_scanner: ^1.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  flutter_svg_provider: ^1.0.6
  cloud_firestore: ^4.14.0
  flutter_native_splash: ^2.3.7
  webview_flutter: ^4.5.0
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  flutter_stripe: ^8.0.0+1
  http: ^1.1.0
  bottom_sheet: ^4.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

# flutter_native_splash:
#   color: "#42a5f5"
#   image: "assets/images/Logo_dananir2.png"

  # android_12:
  #   color: "#42a5f5"
  #   image: assets/images/Logo_dananir2.png


# The following section is specific to Flutter packages.
flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
